--------------------------------------------------------
-- Archivo creado  - lunes-junio-02-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAZA_DE_CAMBIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TAZA_DE_CAMBIO" 
   (	"FECHA" DATE, 
	"TAZA_CAMBIO_DOLLAR" NUMBER, 
	"TAZA_CAMBIO_QUETZALES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TAZA_DE_CAMBIO
SET DEFINE OFF;
Insert into SYSTEM.TAZA_DE_CAMBIO (FECHA,TAZA_CAMBIO_DOLLAR,TAZA_CAMBIO_QUETZALES) values (to_date('26/04/25','DD/MM/RR'),8,1.5);
Insert into SYSTEM.TAZA_DE_CAMBIO (FECHA,TAZA_CAMBIO_DOLLAR,TAZA_CAMBIO_QUETZALES) values (to_date('30/03/25','DD/MM/RR'),7.31,1.3);
Insert into SYSTEM.TAZA_DE_CAMBIO (FECHA,TAZA_CAMBIO_DOLLAR,TAZA_CAMBIO_QUETZALES) values (to_date('02/06/25','DD/MM/RR'),8,1.3);
Insert into SYSTEM.TAZA_DE_CAMBIO (FECHA,TAZA_CAMBIO_DOLLAR,TAZA_CAMBIO_QUETZALES) values (to_date('01/06/25','DD/MM/RR'),8.3,1.8);
Insert into SYSTEM.TAZA_DE_CAMBIO (FECHA,TAZA_CAMBIO_DOLLAR,TAZA_CAMBIO_QUETZALES) values (to_date('31/05/25','DD/MM/RR'),7.8,1.4);
